dappx/urls.py
# dappx/urls.py
from django.conf.urls import url
from dappx import views

# SET THE NAMESPACE!
app_name = 'dappx'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^submission/$',views.submission,name='submission'),
    url(r'^thank/$',views.thank,name='thank')

]

essay/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from dappx import views

urlpatterns = [
    path('admin/', admin.site.urls),
	url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^dappx/',include('dappx.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),

]

dappx/models.py
# dappx/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    Name = models.CharField(max_length=140, default='')
    contact_number = models.CharField(max_length=140, default='')
    State = models.CharField(max_length=140, default='')
    Country = models.CharField(max_length=140, default='')
    DOB = models.DateField(("DOB"), default=datetime.date.today) 

class SubmissionForm(models.Model):
    title= models.CharField(max_length=1000)
    essay= models.CharField(max_length=10000)


def __str__(self):
  return self.user.username

dappx/forms.py
# dappx/forms.py
from django import forms
from dappx.models import UserProfileInfo, SubmissionForm
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        help_texts = {
            'username': None,
        }
        fields = ('username', 'password', 'email')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('Name', 'contact_number', 'State', 'Country', 'DOB')


class SubmissionForm(forms.ModelForm):
    title = forms.CharField(max_length=1000, widget=forms.TextInput(attrs={'class': 'col-751'}))
    essay = forms.CharField(max_length=10000, widget=forms.Textarea(attrs={'class': 'col-752'}))

    class Meta():
        model = SubmissionForm
        fields = ('title', 'essay')

dappx/views.py
from django.shortcuts import render
from dappx.forms import UserForm, UserProfileInfoForm, SubmissionForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages

count = 0


def index(request):
    return render(request, 'dappx/index.html')


@login_required
def special(request):
    return HttpResponse("You are logged in !")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def submission(request):
    form = SubmissionForm(data=request.POST)
    if request.method == 'POST':
        form = SubmissionForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            user.save()
            count = 0
            return HttpResponseRedirect(reverse('dappx:thank'))

    return render(request, 'templates/dappx/index1.html/', {'form': form})


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registered = True
            return HttpResponseRedirect(reverse('dappx:submission'))
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'dappx/registration.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username, password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'dappx/login.html', {})


def thank(request):
    global count
    count += 1

    return HttpResponse("Thank You, your submission number is " + str(count))

templates/dappx/Submission.html
{% extends 'dappx/base.html' %}
{% block body_block %}
<!DOCTYPE html>
<html>
<head>



<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="Content-Script-Type" content="text/javascript">
<meta name="Content-Style-Type" content="text/css">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src='https://kit.fontawesome.com/a076d05399.js'></script>
<style>
* {
  box-sizing: border-box;
}

body { 
background-color: #F6FAFF;
font-family:Comic Sans MS;
}
.hide { position:absolute; top:-1px; left:-1px; width:1px; height:1px; }
.button {
  background-color: #6991FF; 
  border: none;
  color: white;
  padding: 20px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 10px 40px;
  cursor: pointer;
}


input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  resize: vertical;
box-shadow: 1px 1px 1px 1px #aaaaaa;
}

label {
  padding: 12px 12px 12px 0;
  display: inline-block;
}

input[type=submit] {
  background-color: #4CAF50;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  float: right;
}

input[type=submit]:hover {
  background-color: #45a049;
}



.col-751 {
  float: centre;
  width: 100%;
  margin-top: 20px;
  
background: #FFFFFF 0% 0% no-repeat padding-box;
box-shadow: 0px 2px 6px #00000029;
border-radius: 12px;
opacity: 1;
}

.col-752 {
  float: centre;
  width: 100%;
  margin-top: 20px;

background: #FFFFFF 0% 0% no-repeat padding-box;
box-shadow: 0px 2px 6px #00000029;
border-radius: 12px;
opacity: 1;
}

.new {
  border-radius: 5px;
  background-color: #FFE4E4;
  padding: 20px;
box-shadow: 1px 1px 1px 1px #aaaaaa;

 
}

.button4 {border-radius: 12px;
height:50px;
width:200px;
padding-bottom:10px;
padding-top:10px;}
.button5 {border-radius: 12px;
          background-color: azure;
          color: grey;}
.button6 {border-radius: 12px;
          background-color: azure;
          color: grey;}



.t{text-align: center;
display: inline-block;
}
.t1{
color:orange;
margin: 20px;

}
.t2{margin:20px;
}
.t3{margin:20px;padding-left:200px; 
}
.t4{margin:20px;padding-left:0px;}



/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 600px) {
  .col-25, .col-75, input[type=submit] {
    width: 100%;
    margin-top: 0;
  }
}
.ic0{position: absolute;
    top: 0px;
    right: 10px;}
.ic{position: absolute;
    top: 0px;
    right: 0px;}
</style>
</head>
<body>

<div class="kk">
<button class="kk button button4" style="font-family:Montserrat;">New Essay</button>
<button class="kk button button5" style="font-family:Rubik;"><i class="far fa-calendar"></i>    Saved</button>

<button class="kk button button6" style="font-family:Rubik;"><i class="far fa-paper-plane"></i>    Submitted</button>

<script type="text/javascript" text-align="right" style="font-family:Poppins;" >
document.write ('<p class="ic0"><span id="date">', new Date().toLocaleString(), '<\/span>.<\/p>')
if (document.getElementById) onload = function () {
	setInterval ("document.getElementById ('date').firstChild.data = new Date().toLocaleString()", 50)
}
</script>
<img src="/ID728867.png/" class="ic">
</div>
<div class="new">
 <h3 class="t t1" style="font-family:Rubik; color:#FF6B35;"> Hi !</h3>
 <h4 class="t t2" style="font-family:Rubik; color:#2C2C2C;"> Write your essay and help our community to sustain your language from extinction. </h4>
 <h4 class="t t3" style="font-family:Rubik;"> Choose Language </h4>
 <p class="t t4" style="font-family:Rubik; background: #FFFFFF 0% 0% no-repeat padding-box;
box-shadow: 0px 2px 6px #00000029;
border-radius: 12px;
opacity: 1;"> <select style="color: #6991FF;opacity: 1; font-family:Rubik;">
  <option value="Mandari">Mandari</option>
  <option value="Marwadi">Marwadi</option>
  <option value="Tulu">Tulu</option>
  <option value="Tamil">Tamil</option>
</select> </p>
</div>




  <form id="form">
  {% csrf_token %}
{{ form.as_p }}
  <div class="row">
    
    <div class="col-751">
      <input type="text" id="fname" name="firstname" placeholder="Write your title here" style="font-family:Rubik;">
    </div>
  </div>
  
  
  <div class="row">
    
    <div class="col-752">
      <textarea id="subject" name="subject" placeholder="Write your essay here" style="height:300px; font-family:Rubik;"></textarea>
	  <div id="countWord"></div>
    </div>
  </div>
  

 
<input type="submit" value="Submit" id="countButton"></a>
  </form>
  <a href="/"><div class="row" id="countButton">
    
	<p>Thank You, your submission number is <span id="displayCount">0</span></p>
  </div>
  <script type="text/javascript">
      var count = 0;
      var button = document.getElementById("countButton");
      var display = document.getElementById("displayCount");

      button.onclick = function(){
        count++;
        display.innerHTML = count;
      }
    </script>
	    
	    

 
	

 
	
	
</body>
</html>
{% endblock %}

templates/dappx/index.html
{% extends "dappx/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
        <ul>
            <li>Head on to Register tab above</li>
            <li>Fill the information and make sure to enter the correct format of email</li>
            <li>Click on Register button, you will be redirected to submission page</li>
            <li>Enter the details in submission page and click on submission button</li>
            <li>Thank you message with submission number will be displayed</li>
            <li>Now go back to the starting page by clicking on back button on your browser two times or go to this link again- https://enigmatic-brook-01257.herokuapp.com/  </li>
            <li>Go to the admin tab and enter username - admin  password - youknowme</li>
            <li>You can find your data in User profile infos and Submission forms in the latest object</li>
        </ul>  
    {% else %}
        <ul>
            <li>Head on to Register tab above</li>
            <li>Fill the information and make sure to enter the correct format of email</li>
            <li>Click on Register button, you will be redirected to submission page</li>
            <li>Enter the details in submission page and click on submission button</li>
            <li>Thank you message with submission number will be displayed</li>
            <li>Now go back to the starting page by clicking on back button on your browser two times or go to this link again- https://enigmatic-brook-01257.herokuapp.com/  </li>
            <li>Go to the admin tab and enter username - admin  password - youknowme</li>
            <li>You can find your data in User profile infos and Submission forms in the latest object</li>
        </ul>    
    {% endif %}
  </div>
</div>
{% endblock %}

templates/dappx/login.html
{% extends 'dappx/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'dappx:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

templates/dappx/register/Submission.html
{% extends 'dappx/base.html' %}
{% block body_block %}
<!DOCTYPE html>
<html>
<head>



<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="Content-Script-Type" content="text/javascript">
<meta name="Content-Style-Type" content="text/css">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src='https://kit.fontawesome.com/a076d05399.js'></script>
<style>
* {
  box-sizing: border-box;
}

body { 
background-color: #F6FAFF;
font-family:Comic Sans MS;
}
.hide { position:absolute; top:-1px; left:-1px; width:1px; height:1px; }
.button {
  background-color: #6991FF; 
  border: none;
  color: white;
  padding: 20px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 10px 40px;
  cursor: pointer;
}


input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  resize: vertical;
box-shadow: 1px 1px 1px 1px #aaaaaa;
}

label {
  padding: 12px 12px 12px 0;
  display: inline-block;
}

input[type=submit] {
  background-color: #4CAF50;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  float: right;
}

input[type=submit]:hover {
  background-color: #45a049;
}



.col-751 {
  float: centre;
  width: 100%;
  margin-top: 20px;
  
background: #FFFFFF 0% 0% no-repeat padding-box;
box-shadow: 0px 2px 6px #00000029;
border-radius: 12px;
opacity: 1;
}

.col-752 {
  float: centre;
  width: 100%;
  margin-top: 20px;

background: #FFFFFF 0% 0% no-repeat padding-box;
box-shadow: 0px 2px 6px #00000029;
border-radius: 12px;
opacity: 1;
}

.new {
  border-radius: 5px;
  background-color: #FFE4E4;
  padding: 20px;
box-shadow: 1px 1px 1px 1px #aaaaaa;

 
}

.button4 {border-radius: 12px;
height:50px;
width:200px;
padding-bottom:10px;
padding-top:10px;}
.button5 {border-radius: 12px;
          background-color: azure;
          color: grey;}
.button6 {border-radius: 12px;
          background-color: azure;
          color: grey;}



.t{text-align: center;
display: inline-block;
}
.t1{
color:orange;
margin: 20px;

}
.t2{margin:20px;
}
.t3{margin:20px;padding-left:200px; 
}
.t4{margin:20px;padding-left:0px;}



/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 600px) {
  .col-25, .col-75, input[type=submit] {
    width: 100%;
    margin-top: 0;
  }
}
.ic0{position: absolute;
    top: 0px;
    right: 10px;}
.ic{position: absolute;
    top: 0px;
    right: 0px;}
</style>
</head>
<body>

<div class="kk">
<button class="kk button button4" style="font-family:Montserrat;">New Essay</button>
<button class="kk button button5" style="font-family:Rubik;"><i class="far fa-calendar"></i>    Saved</button>

<button class="kk button button6" style="font-family:Rubik;"><i class="far fa-paper-plane"></i>    Submitted</button>

<script type="text/javascript" text-align="right" style="font-family:Poppins;" >
document.write ('<p class="ic0"><span id="date">', new Date().toLocaleString(), '<\/span>.<\/p>')
if (document.getElementById) onload = function () {
	setInterval ("document.getElementById ('date').firstChild.data = new Date().toLocaleString()", 50)
}
</script>
<img src="/ID728867.png/" class="ic">
</div>
<div class="new">
 <h3 class="t t1" style="font-family:Rubik; color:#FF6B35;"> Hi !</h3>
 <h4 class="t t2" style="font-family:Rubik; color:#2C2C2C;"> Write your essay and help our community to sustain your language from extinction. </h4>
 <h4 class="t t3" style="font-family:Rubik;"> Choose Language </h4>
 <p class="t t4" style="font-family:Rubik; background: #FFFFFF 0% 0% no-repeat padding-box;
box-shadow: 0px 2px 6px #00000029;
border-radius: 12px;
opacity: 1;"> <select style="color: #6991FF;opacity: 1; font-family:Rubik;">
  <option value="Mandari">Mandari</option>
  <option value="Marwadi">Marwadi</option>
  <option value="Tulu">Tulu</option>
  <option value="Tamil">Tamil</option>
</select> </p>
</div>




  <form id="form">
  <div class="row">
    
    <div class="col-751">
      <input type="text" id="fname" name="firstname" placeholder="Write your title here" style="font-family:Rubik;">
    </div>
  </div>
  
  
  <div class="row">
    
    <div class="col-752">
      <textarea id="subject" name="subject" placeholder="Write your essay here" style="height:300px; font-family:Rubik;"></textarea>
      <div id="countWord"></div>
    </div>
  </div>
  

 

  </form>
  <a href="/"><div class="row" id="countButton">
    <input type="submit" value="Submit" id="countButton"></a>
    <p>Thank You, your submission number is <span id="displayCount">0</span></p>
  </div>
  <script type="text/javascript">
      var count = 0;
      var button = document.getElementById("countButton");
      var display = document.getElementById("displayCount");

      button.onclick = function(){
        count++;
        display.innerHTML = count;
      }
    </script>
    
    

 


 


</body>
</html>
{% endblock %}

templates/dappx/thank.html
<html lang="en">
<head></head>
<body>
<h1>Thank You, your submission number is <span id="displayCount">0</span></h1>
<script type="text/javascript">
      var count = 0;
      var display = document.getElementById("displayCount");
      count++;
      display.innerHTML = count;
    </script>
</body>
</html>    